layout_spectrum: 0
typography_spectrum: 0.5255319
color:
  lightness: 1
  brandStrength: 0.658438
  saturation: 0.2617021
  rhythmicContrast: 0.6489362
  brandColors:
    - '#E0DFE0'
    - '#787678'
    - '#4C4A4C'
name: Joleen Willis Wedding Photography
